### ISSUE TITLE
Use image meta data programme [$115]

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#101]
# The gallery app should be able to add/edit/delete various fields linked to a media file.

Lots of the information is stored in XMP/IPTC/EXIF fields and this should be automatically imported, but a user should also be able to fill empty fields and add new ones.

This can then be used for:
- sorting by date taken as opposed to date uploaded
- sorting by colour (Exif data)
- sorting by size
- sorting by person (Exif data)
- virtual views. Date based albums, tags based albums, location based albums, etc #95 
## Pre-requirements
- [ ] Collect EXIF/XMP/IPTC data (#550)
## Programme
- [ ] Sort by "picture taken" date #221
- [ ] Rotate pictures #236
- [ ] Add meta data description to the slideshow #525
- [ ] Filter using meta data properties #531
- [ ] Edit meta data properties
- [ ] Sort by "face" using meta data #551

_Please add bounties to individual issues_
##

**Comment by oparoz** [comment]
@cbxk1xg - Do you have any experience with this?

**Comment by rhatguy** [comment]
Another useful piece of metadata would be face tagging.  Being able to search for photos of a particular person or persons or even create virtual albums containing only a specific person is a huge help in a large photo collection.  If a user has spent the significant amount of time it takes to tag all of their photos, being able to take advantage of those tags is huge.

**Comment by oparoz** [comment]
@rhatguy - That would be great, but I'm not aware of any free face tagging library we could use. Are you?

**Comment by rhatguy** [comment]
exiftool is able to read the data from the image as shown below via command line.  I'm not terribly familiar with how to pull this type of data from within php's EXIF library.  There are some guidelines for storing face detection data put together by the metadataworking group specifically in section 5.9 in the linked pdf below.  Google Picasa has conformed to this standard and is able to search for faces and add the tags directly into the files metadata.

http://www.metadataworkinggroup.com/pdf/mwg_guidance.pdf

# exiftool IMG_6420.JPG  | egrep -i region

Region Applied To Dimensions W  : 3456
Region Applied To Dimensions H  : 5184
Region Applied To Dimensions Unit: pixel
Region Name                     : Travis Kelley
Region Type                     : Face
Region Area X                   : 0.531829
Region Area Y                   : 0.371238
Region Area W                   : 0.0983796
Region Area H                   : 0.0788966
Region Area Unit                : normalized

**Comment by oparoz** [comment]
Thanks! :)
If it's stored in the exif data, we should be able to extract and use it.

**Comment by d3anp** [comment]
It would be excellent if the metadata was indexed and searchable. For example:
- show photos with a specifc **camera**
- show photos taken in **Australia** in **2014** of **Person X**

Please add and use metadata from the embedded EXIF. It allows for a truly portable photo collection.

**Comment by oparoz** [comment]
Moving comments implementation to https://github.com/owncloud/galleryplus/issues/176

**Comment by oparoz** [comment]
So, good news, @patman15 is going to work on the first step towards having full meta-data support. Once [this initial piece of work](https://github.com/owncloud/gallery/issues/221) is in, it should be fairly simple to implement some of the features listed here.

We need designers to figure out the best way to design the controls. I'm thinking of using a ribbon interface which  should give plenty of room for buttons for basic operations.

**Comment by Bugsbane** [comment]
What design help is needed on this? The addition of the tags framework in ownCloud 9 seems like the perfect time to revisit this.

**Comment by oparoz** [comment]
@Bugsbane - I've added a list of issues to the OP. Those are the ones needing designers.

Filtering via tags is in https://github.com/owncloud/gallery/issues/532. The main problem affecting all filters though is the lack of a navigation sidebar https://github.com/owncloud/gallery/issues/401

**Comment by Bugsbane** [comment]
So..... what exactly is it, that a designer could do to help with these listed issues? It's still very much unclear. I took a scan of all of the issues in the OP that had links to them, and I didn't see any request for designer help in any of them. So is the needed help... Wireframe mockups for potential UI's? Graphical elements for already decided UI's? New interface ideas? Something else entirely?

**Comment by oparoz** [comment]
In #525, we need designers to find a way to display a description which works in all cases (desktop/mobile, portrait/landscape).

In #221, we need to find a way to let the user know that exif data is available and that it can be used for date sorting. If we mix upload date and picture taken date, users will end up with images arranged in an unpredictable order.

For the navigation panel, I was thinking of re-using what is currently used in Files, making it a no-brainer for users to filter their collection.

If you have CSS/JS skills, you can try to fix #401. That way we can implement favourites and tags sooner. I'm happy to provide some leads.

**Comment by oparoz** [comment]
Moved the meta data app to #550. This issue is now purely about tracking the programme.

**Comment by oparoz** [comment]
Created "Sort by "face" using meta data" #551

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#26
