### ISSUE TITLE
Too many preview images are generated in the thumbnail directories.

### ISSUE THREAD

**Issue by setnes** [owncloud/gallery#157]
Preview images are generated for the size of the browser window.  For example, if someone views images with a browser sized at 1355x950, all of the preview images are are created at that size.  Later, if someone views images with a browser sized at 1349x943, all of the preview images are created again at this new size.

Also, preview images are generated for image sizes larger than the actual size of the image even if preview_max_scale_factor is set to 1.  This results in many duplicate files of the same resolution when the image is smaller than the window sizes.  Instead, we should serve the *-max.png in these situations instead of creating additional previews.

All of these extra preview images cause unnecessary overhead and storage on the server side.  We should create preview images that are **close to** the browser size instead of **exactly** the browser size.

getPreviewUrl in galleryutility.js can be adjusted to change the requested image size to normalize the requests to image sizes that have a greater probability of existing.  This is discussed under #54.

**Comment by setnes** [comment]
The following code finds the smallest width and length dimensions that are multiples of 100 and are still greater than the window size of the browser.  This was tweaked to handle the case where the window size is, in fact, a multiple of 100.  My original statements would give 100 pixels more than it needed in that situation.

This goes in getPreviewUrl in galleryutility.js.

```
/* Find the next larger image width and length. */
if ( width % 100 != 0 ) {
      width = ( width + 100 ) - ( width % 100 );
}

if ( height % 100 != 0 ) {
      height = ( height + 100 ) - ( height % 100 );
}
```

There's still room for improvement here.  An image size of 1000x500, could get requested at 1000x1000, 1000x900, 1000x600, etc.  All of those would still result in different preview images that have identical actual resolutions.  We need some aspect ratio, longest edge comparison logic.

**Comment by setnes** [comment]
This isn't quite right yet.  The image size requesting works fine, but the slideshow is not set to have the browser scale anything.  How can that be controlled?

**Comment by oparoz** [comment]
I completely agree with the OP. It was on my todo list to fix core so that it wouldn't create previews larger than the max size or the original size.

So here is the todo:
- [x] Never create a cached preview larger than the max preview https://github.com/owncloud/core/issues/16545
- [x] Don't store the exact same preview every time we check for its existence https://github.com/owncloud/core/issues/16544
- [ ] Create preview categories https://github.com/owncloud/core/issues/8196
- [x] Fix the slideshow to make it possible to use previews which are larger than the viewport

Regarding the slideshow not playing ball, I think I ran into the same issue when trying to fix https://github.com/owncloud/galleryplus/issues/142. 
We're providing Bigshot with the image dimensions and it's not resizing it to fit the viewport
https://github.com/owncloud/galleryplus/blob/master/js/slideshowzoomablepreview.js#L46

**Comment by setnes** [comment]
I got the bigshot slideshow to "play ball" so to speak.  

Inside slideshowzoomablepreview.js in the startBigshot function, I set maxZoom to 0 to prevent increasing images beyond their actual size.  I then set minZoom to -1 to allow for some downsizing.  After these are set, I added the following to the end of the function...

```
this.zoomable.zoomToFit();
```

And like magic, everything started scaling correctly when using my "multiples of 100" sized images.  I'm ignoring the owncloud scale factor setting for now.  I'm also not sure where the _best_ place is for zoomToFit to be called.

It looks like bigshot fully supported this, it just wasn't going to fit the image unless we asked it to.  :)

This also seems to help for #142.

**Comment by setnes** [comment]
If we request length and width both based on the longest edge in addition to the "multiple of something" logic, that would prevent the 1000x900, 1000x800, 1000x600 all getting created.  Instead we'd just see 1000x1000.  In addition to that, it would go a long way to solve #142 because a rotation at this point would still use the same, scaled image.  In my prior comment, I put zoomToFit in a spot where the "next" image after rotation is displayed correctly.  I believe the minZoom needs to be -2 instead of -1 though to cover better in the case of extreme browser window aspect ratios.

Here's my new logic that adjusts the requested size.

```
                getPreviewUrl: function (image) {
                        var width = $(window).width() * window.devicePixelRatio;
                        var height = $(window).height() * window.devicePixelRatio;

                        /* Find value of longest edge. */
                        var longEdge = Math.max( width, height );

                        /* Find the next larger image size. */
                        if ( longEdge % 100 != 0 ){
                                longEdge = ( longEdge + 100 ) - ( longEdge % 100 );
                        } 

                        /* jshint camelcase: false */
                        var params = {
                                file: image,
                                x: longEdge,
                                y: longEdge,
                                requesttoken: oc_requesttoken
                        };
                        return this.buildGalleryUrl('preview', '', params);
                },
```

I apologize for all of these posts.  I'm having fun.  :)

**Comment by oparoz** [comment]
Thanks for testing this. I'm busy fixing core's preview class and then I'll take a look :).
Using a square was exactly what I did for #142,  but I was having no luck with device rotation. Hopefully, you've fixed it :)
Make sure to test with 4k pictures, as well as 50x50 animated Gifs. Both have to be viewable and zoomable.

**Comment by setnes** [comment]
Large and small images, and animated gifs all work, but I broke zooming beyond the actual size of the image by hardcoding maxZoom to 0.  I did this because I wanted images smaller than the window size to display 1:1 instead of zoomed to the size of the window.  I think I can get this zooming to work again (if desirable) by doing some comparisons and perhaps using something like fitZoom and specifying the starting zoom size.  I'd start with the window size or 1:1 (whichever is smaller)... and then maybe we'd be able to put maxZoom back to what it was.

Device rotation works reasonably OK, except it's not perfect on the current image.  Bigshot does attempt to do the right thing here though... but it's not perfect for some reason.  Everything is great on the next image and beyond after a rotate though.

**Comment by oparoz** [comment]
Because Bigshot is embedded in the slideshow code, there may be events missing to tell it that the layout as changed.

**Comment by setnes** [comment]
Ok.  I fixed the zooming again.  Here's my latest "startBigshot."  The only changes I have in here now are the minZoom is hardcoded to -2 instead of 0, and there's an IF block at the end of the function that compares the image size to the window size to decide if zoomToFit should be called.

This, coupled with my version of "getPreviewUrl" from above, is working quite nicely for me.  We get fewer (but consistent) thumbnail files, zooming still works, and the image is large enough to rotate and still fills the space.

I tested the device rotation further.  After rotation, the current image is displayed 1:1 without scaling, all further images are scaled properly (when they hit the new zoomToFit call).  This feels better than before simply because the current image is always large enough to fill the screen.  There might be a way to fix this further (the image at the time of rotation), but I think this is a big improvement either way.

```
                startBigshot: function (image, currentImage) {
                        this.currentImage = currentImage;
                        if (this.zoomable !== null) {
                                this.zoomable.dispose();
                                this.zoomable = null;
                        }
                        var maxZoom = this.maxZoom;
                        var imgWidth = image.naturalWidth / window.devicePixelRatio;
                        var imgHeight = image.naturalHeight / window.devicePixelRatio;
                        if (imgWidth < this.smallImageDimension && imgHeight < this.smallImageDimension) {
                                maxZoom += 3;
                                this.currentImage.isSmallImage = true;
                        }
                        this.zoomable = new bigshot.SimpleImage(new bigshot.ImageParameters({
                                container: this.element,
                                maxZoom: maxZoom,
                                minZoom: -2,
                                touchUI: false,
                                width: imgWidth,
                                height: imgHeight
                        }), image);
                        if (this.fullScreen === null && this.currentImage.mimeType !== 'image/svg+xml') {
                                this._resetZoom();
                        }

                        // prevent zoom-on-doubleClick
                        this.zoomable.addEventListener('dblclick', function (ie) {
                                ie.preventDefault();
                        });

                        // If the image is at all bigger than the window, call zoomToFit.
                        if ( $(window).width() < imgWidth || $(window).height() < imgHeight ) {
                                this.zoomable.zoomToFit();
                        }

                },
```

**Comment by oparoz** [comment]
Thanks very much for your work!
If you know how, it would be great if you could prepare a PR. If not I'll do it.

**Comment by setnes** [comment]
I don't have experience with git yet, but I'm familiar with Subversion.  Is there a fast set of instructions for this somewhere?  :)

**Comment by oparoz** [comment]
https://help.github.com/articles/set-up-git/

Github makes it easy to fork and push code. For larger contributions, I would recommend getting something like PHPStorm which can run commands from within the IDE.

**Comment by setnes** [comment]
I really hope I did that correctly.  I see you added etag to the parameters.  I made my pull request changes on top of that, but didn't test with it.

**Comment by oparoz** [comment]
Thanks for the PR :).
The etag is to make sure the picture gets refreshed, but it's not perfect...It shouldn't have an impact on your work.

I'll comment on the PR once I get a chance to test it.
You will need to modify another file as your modification only has an impact on the Gallery slideshow, but the Files app needs those changes as well.

**Comment by setnes** [comment]
Let me guess... it's completely different code. Do we only need to worry about how the preview images are generated outside of gallery, or does other stuff actually start Bigshot directly?

Is it generatePreviewUrl in /apps/files/js/filelist.js ?

Do you worry about what's in /apps/files_sharing/js/public.js ?

**Comment by oparoz** [comment]
No, it's the same code
https://github.com/owncloud/galleryplus/blob/master/js/galleryfileaction.js#L71

And we don't have to worry about anything else since we're responsible for the slideshow.

**Comment by setnes** [comment]
I fixed galleryfileaction.js to work the same with multiples of 100 and square request sizes.

**Comment by oparoz** [comment]
Cool. Do the keyboard shortcuts still work as expected? 0/9 or up/down One should fill the screen, the other send the picture back to its original loading size, for pics which are too small to fit.

**Comment by setnes** [comment]
The buttons still work.  It's worth noting something though.  The up arrow fits the image to the screen and the down arrow loads the image 1:1.  Since we're fitting to the screen for anything larger than the screen and loading 1:1 for anything smaller, these buttons feel a bit reversed depending on if the image presented is larger or smaller than the screen.  I like it this way, but thought I'd point it out.

**Comment by oparoz** [comment]
Think FPS. If you're pressing up in a game, you're moving forward and thus objects get bigger. Same with the mouse wheel usually. Maybe it's like scrolling on a touch device. It feels reverse at first, but then you start feeling the way desktops are doing it is wrong :)

**Comment by setnes** [comment]
Actually, what I meant by reversed is that sometimes clicking down will result in a larger image and sometimes clicking down will result in a smaller image.  In both cases we're going to the 1:1 image though.  Likewise, clicking up will sometimes make the image smaller to fit the screen and sometimes it will make the image larger to fit the screen.  The buttons don't have anything to do with "get bigger" or "get smaller"... even if that's how they felt before.

**Comment by oparoz** [comment]
Ah, yes and my analogy is wrong... The way it was designed was fit the screen or go to original size, so if you're zoomed out and go to original size, then the image will grow.
Maybe I should remove up/down and i/o, keep 0/9 and introduce o/m (original/maximum). F is already fullscreen.

**Comment by setnes** [comment]
Yeah..  I kinda like having one hand on the arrows... but it is a bit different now that the original isn't always the same size or smaller than the window.
