### ISSUE TITLE
Redesign the slideshow

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#255]
If we stay with the current version of the slideshow, we need to fix and implement a few things. The alternative is to focus on something like Photoswipe https://github.com/owncloud/gallery/issues/158
### Must have
- [x] Show file name in the slideshow #237
- [ ] Show file actions in the slideshow (sharing, rename, favorite, delete. download is already there) #68
- [x] Make background colour switcher optional #226 
- [x] Make the slideshow controls work with a light background  #51
- [ ] Add full screen button in slideshow #252 
### Should have
- [ ] Mobile users should be able to "swipe" through photos instead of clicking on icons #141
- [ ] Automatically select an appropriate background colour based on the image's luminance #84 
### Could have
- [ ] Settings (something like minimal/advanced interface switch, etc.) #4 – if we feel we can not do it automatically
- [ ] Let the user rotate pictures which support EXIF #236 
- [ ] Add comments to slideshow #176
- [ ] Various picture transitions in the slideshow #83 
- [ ] Add HD option which would send the original pictures to the slideshow #193
##

**Comment by oparoz** [comment]
@jancborchardt @demattin @setnes @libasys Feel free to add to the list if required.

**Comment by libasys** [comment]
HD option is a good idea! Have you made a scribble for the redesign, how it could, should, incl. buttons?

**Comment by oparoz** [comment]
> Have you made a scribble for the redesign, how it could, should, incl. buttons?

I haven't, but @jancborchardt already has an idea of what it should look like. A mockup would be nice indeed :)

**Comment by jancborchardt** [comment]
@oparoz I added

> Show file actions in the slideshow (sharing, rename, favorite, delete. download is already there)

as second item because I actually think that’s the most important thing for the slideshow. Currently you need to exit the viewer to perform any actions on the image.

**Comment by oparoz** [comment]
@jancborchardt - Yes, that's fine. Being aware that those actions will end up somewhere will help with the design.

**Comment by jospoortvliet** [comment]
@jancborchardt ha, an use for the new sidebar perhaps?

**Comment by Visual-Notes** [comment]
I hope that displaying the file name and additional links for actions in the lightbox/slideshow will be optional, so it could also be turned off.
For my taste, there are already enough buttons visible in the slideshow.

Best thing would be to make most of them optional (except for Previous, Next and Close).
I think, an auto-hiding sidebar would be an alternative for providing additional buttons, so that the slideshow interface is kept clean and allows users to concentrate on watching the pictures.

Btw, i wonder why the esc key doesn't close the slideshow, since this is the default behavior of most lightboxes/slideshows.

**Comment by jancborchardt** [comment]
The slideshow interface will be kept clean, no worries. The actions will hide after some time too, like it is now. We’ll not include options for everything of these, because the ability to share or favorite an image from the detail view is a pretty basic function.

> Btw, i wonder why the esc key doesn't close the slideshow, since this is the default behavior of most lightboxes/slideshows.

@africanforest please open a separate issue about this.

**Comment by oparoz** [comment]
An example 
![](https://raw.githubusercontent.com/photo/frontend/master/files/creative/screenshots/web/lightbox.jpg)

**Comment by Visual-Notes** [comment]
Trovebox seems not being developped any more. Are you planning to fork it?

**Comment by oparoz** [comment]
No, but someone is talking about either making an ownCloud app of it or to build a connector.

I think we can have Trovebox as a goal for Gallery, with some additional missing features. They do look very similar and share some common goals if you look at the list of feature requests on here.

**Comment by youphyun** [comment]
Everpix dead, Loom aquired by Dropbox, Picturelife aquired by StreamNation in early 2015 and also solely US based (while they still support US based S3 buckets for existing users it is very unknown what will happen), Trovebox that was originally crowdfunded as OpenPhoto is dead. The github open source version has only limited features and is not actively developed anymore. Why does every photo storage startup dies or gets acquired? So far, no one has been able to build a beautiful digital home for our photos and turn it into a sustainable, independent business. It would be indeed great if ownCloud could add more features to the Picture/Gallery app so this gap is filled. I am sure there is much interest and even willingness to fund this via BountySource or any other crowdfunding solution.

**Comment by jancborchardt** [comment]
@joephein we’re working on it! :) The good part is that ownCloud Gallery works simply on top of files. You can already support us on Bountysource via https://www.bountysource.com/teams/owncloud – or just pay @oparoz directly so he can commit more time to working on Gallery. ; )

**Comment by oparoz** [comment]
@joephein 

> Why does every photo storage startup dies

The market is pretty crowded in terms of commercial offerings and so it's difficult to find a working business model with a unique proposition. You have to sell subscriptions in order to keep the open source version alive since you can't sell ads or collect personal info and you would need a million dollars to realise the vision.
Look at what happened to App.net. It's not easy.

>  or gets acquired?

That's the name of the game. Build it, grow it, sell it, next.
Even if the goal is to create something really useful for a community, it's difficult to turn down offers by big companies when you've got bills to pay or still have lots of ideas for new projects.

>  It would be indeed great if ownCloud could add more features to the Picture/Gallery app so this gap is filled

I agree. If you can't build a team to build a new app or connect an existing one built by a team, you're better off working on Gallery. One advantage this app has is that it can benefit of the experience of `core` software engineers who can help steer it in the right direction when need be. I've looked at a few alternatives recently and even though some of them are well written and have some unique features, I don't necessarily trust the one person working on the project. The author may be brilliant at building dazzling front-ends, but may not write database queries that well or have built a solid, secure foundation for his/her app. 

> I am sure there is much interest

That's difficult to assess. People seem to take core apps for granted, then start to rely on them and come back to complain when things break :)

> even willingness to fund this via BountySource or any other crowdfunding solution

I believe this to be the best solution. It theoretically reaches more people than Github or the forums, makes it possible to define clear goals which are important to users and to hire software engineers to get things done.
The alternative is for businesses to start using ownCloud and pay ownCloud shops for customisations, but I'm not sure many would see Gallery as a priority

**Comment by Yetangitu** [comment]
https://github.com/photo/frontend/issues/1570#issuecomment-154257075

**Comment by jancborchardt** [comment]
> The current Owncloud apps which partly cover this area (Gallery and Gallery+) are not up to this task due to a lack of performance and features, especially when presented with a 'large' image collection.

@Yetangitu maybe you can expand on that in a separate issue? Having yet another separate gallery app doesn’t sound like the best idea – as proven by a history of »forked« and then subsequently unmaintained apps which only had one main developer and just stalled at some point. So let’s work together on this! :)

**Comment by oparoz** [comment]
@jancborchardt - It's due to a lack of understanding of how ownCloud works. An external gallery app is going to experience some of the same slowdowns since the files would be fed from ownCloud.

**Comment by Yetangitu** [comment]
As to whether an external app fed through Owncloud would experience the same slowdowns fully depends on the performance of the sharing subsystem and nothing else. As long as Owncloud is able to shuffle files at a reasonable rate it should be able to keep up. In the described use case Owncloud would be used so provide full-size images while Trovebox would serve scaled-down images (which it is able to do at server speed). Owncloud would serve as an image source and -manager, Trovebox would be a loosely-coupled front-end. In other words it is not a direct competitor or replacement for Gallery(+) which - as far as I can see - are mostly intended for use by logged-in Owncloud users. Trovebox is mostly meant to be browsed by external, anonymous users.

**Comment by oparoz** [comment]
> As to whether an external app fed through Owncloud would experience the same slowdowns fully depends on the performance of the sharing subsystem and nothing else. 

Exactly and that's the reason you're going to experience some of the same slowdowns for listing files or accessing the large previews. The only (and major) benefit you'll get will be from your local thumbnails cache.
I've provided more detailed in the Trovebox thread.

> while Trovebox would serve scaled-down images

This would make Trovebox slower than Gallery from the 2nd time a folder is opened since the latter would serve smaller thumbnails.

>  are mostly intended for use by logged-in Owncloud users

I don't agree with this statement, but I may use ownCloud differently.

Again, I think that if Trovebox can build a team and offer a service to a sub-set of ownCloud users, it may be a viable option. It could even use the Gallery API which should be a better fit that the `core` API, but if the goal is just to try and offer better performance, I think there are better uses for all those available coding hours.

**Comment by Yetangitu** [comment]
I commented in the Trovebox thread...

https://github.com/photo/frontend/issues/1570#issuecomment-154409891

**Comment by jancborchardt** [comment]
@Yetangitu @oparoz let’s do this in a separate issue please as I said. This is not relevant in here.

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#60
