### ISSUE TITLE
Dealing with errors programme

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#46]
This is a meta ticket which tracks all the various work being done to improve the reliability of the app
#### Loading the app
- [x] Fail gracefully when something unpredictable happens in the backend https://github.com/interfasys/galleryplus/issues/45
- [x] Try to find a working folder, based on the given location https://github.com/interfasys/galleryplus/issues/44
#### Getting thumbnails
- [x] The backend should send back a 404 status if we can't access the file and a 500 status if we can't generate the thumbnail
- [x] Remove 404 thumbnails from the view if they don't belong to an album
- [x] Show a media type icon for 505 thumbnails, unless they belong to an album
- [x] Only show proper thumbnails in the album representation. There is no point showing blank or media type thumbnails
### Slideshow
- [x] Do no load previews of files which have a media type icon thumbnail https://github.com/interfasys/galleryplus/issues/33
- [x] Download previews of files which have a media type icon thumbnail  https://github.com/interfasys/galleryplus/issues/34
- [x] On the files side, show an error message in the slideshow if we receive a broken thumbnail. We currently can't know before receiving it https://github.com/interfasys/galleryplus/issues/47

Feel free to add your thoughts and to raise new issues to address specific problems.
