### ISSUE TITLE
Make the slideshow controls work with a light background

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#51]
The current controls icons are dark grey and that works well with a black background as it's non-intrusive, but as soon as a picture with a white background fills the screen or if we manually switch the background to white to better see dark pictures with a transparent background, then we can't use the controls, as they become invisible.

@jancborchardt, feel free to chime in and discuss possible solutions.
## TODO

All that remains are bugs which need to be fixed
- [x] Clean up the icons
- [x] Add missing icons

**Comment by jancborchardt** [comment]
The solution for this is to give the controls a slight dark faded border around them. If anyone takes this up that would be great.

**Comment by oparoz** [comment]
Anyone? :) @jancborchardt @tomneedham @raghunayyar

**Comment by jancborchardt** [comment]
@oparoz I’m experimenting with giving the control icons a slight white/bright shadow (not too extreme). Will do a pull request later.

**Comment by oparoz** [comment]
Nice, thanks :)

**Comment by oparoz** [comment]
Re-opening so that we don't forget about the remaining bug

![](https://cloud.githubusercontent.com/assets/323220/10113489/34d3d754-63e5-11e5-89dc-6b04adac7709.png)

**Comment by oparoz** [comment]
Also, the download and "brightness" icons don't have the new look.

**Comment by ghost** [comment]
This bug will fall off 8.2 if not resolved by 6 Oct

**Comment by oparoz** [comment]
Moving to 9.0 as nobody will be able to fix this on time.

**Comment by oparoz** [comment]
All that remains are bugs which need to be fixed
- [ ] Clean up the icons
- [ ] Add missing icons

**Comment by ghost** [comment]
@oparoz @jancborchardt totally unclear to me who's working / planning to work on the remaining bugs

**Comment by oparoz** [comment]
ownCloud designers need to fix the icons in core and replace the 2 in Gallery which use fontawesome with custom ownCloud ones.

I've copied the TODO to the OP

**Comment by ghost** [comment]
Not sure who "ownCloud designers" actually is. Sorry if I am being dense about that

**Comment by oparoz** [comment]
@jancborchardt or a member of @owncloud/designers who can fix the remaining problems.

**Comment by jancborchardt** [comment]
@oparoz can you be more specific? I assume:
- the download icon needs a version with shadow
- what’s the issue with that extra shadow on the play icon you posted above? Seems like a JS or CSS issue rather than an icon issue, with loading the pause icon partially?
- what is the brightness icon?

**Comment by oparoz** [comment]
> the download icon needs a version with shadow

Correct

> what’s the issue with that extra shadow on the play icon you posted above? Seems like a JS or CSS issue rather than an icon issue, with loading the pause icon partially?

It could very well be since I don't see the artifact when looking at the images on their own

> what is the brightness icon?

This one: https://github.com/owncloud/gallery/blob/master/img/toggle.png

I picked the most relevant one from font awesome, but it's too fat now that the other ones have been thinned down and it needs a shadow

**Comment by jancborchardt** [comment]
@oparoz I will take care of the download and brightness toggle icons to give them shadow. Can you fix the JS/CSS issue with the pause icon?

**Comment by oparoz** [comment]
OK, I will try :)

**Comment by jancborchardt** [comment]
@oparoz see the pull requests I opened for the icons. :)

About the pause icon shadow glitch: This is definitely a JS issue. When you initially view a picture, it looks ok. As soon as you play and then directly pause, the shadow appears. That seems like the pause icon is not correctly hidden by JS.

**Comment by oparoz** [comment]
> About the pause icon shadow glitch: This is definitely a JS issue. When you initially view a picture, it looks ok. As soon as you play and then directly pause, the shadow appears. That seems like the pause icon is not correctly hidden by JS.

Looking at it in debug mode, it seems to be some CSS issue. The whole element is supposed to be hidden, but the image isn't.

Could be a z-index problem

**Comment by oparoz** [comment]
Found the problem

**Comment by oparoz** [comment]
Fixes are in #533 and #534

**Comment by ghost** [comment]
@jancborchardt @MorrisJobke can you review the PR's? Last step before merging...

**Comment by ghost** [comment]
ping @jancborchardt @MorrisJobke @PVince81

**Comment by jancborchardt** [comment]
Reviewed and merged both.
