### ISSUE TITLE
Filter content using meta data properties

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#531]
## Feature request

**User type**: All

**User level**: Intermediate
### Description

Let users filter the content of Gallery using meta data properties such as date, tag, colour, size, etc.

This probably requires the use of a navigation sidebar on the left to be able to tap on collected properties or to type a criteria

Advanced users could simply use the search field
### Benefit / value

Being able to quickly reach specific pictures before performing another action 
### Programme
- [ ] Implement left sidebar, like in Files https://github.com/owncloud/gallery/issues/401
- [ ] Show favourites #230 
- [ ] Flat view - all images in current and sub-directories #95
- [ ] Filter by tag #532
- [ ] Filter by location #698 
##

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#115
