### ISSUE TITLE
[Strictly 10.0.9] Gallery 16.1.0 release checklist

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/gallery#761]
When marking a task as done, please add your name to the task!

### Reason
@PVince81 - please fill in details on the requirements for release
- Release needed for https://github.com/owncloud/gallery/pull/738 (minor fix)
- Solves https://github.com/owncloud/files_primary_s3/issues/72

### QA
- [x] Create release branch
- [x] Create "16.1.0" Testplan" https://github.com/owncloud/gallery/issues/771 @davitol
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) @davitol

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Documentation
- [ ] Changes in the docs needed?

### Build & Marketplace release

- [x] Bump version in info.xml @DeepDiver1975 
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' @patrickjahns
- [x] Create github tag for '$version' @patrickjahns
- [x] Build and sign tarball from github tag '$version' @patrickjahns
- [x] Upload to marketplace @patrickjahns
- [x] Send mail to release-coordination with link to this ticket and to the changelog @patrickjahns
- [x] Rename QA milestone to '$version' @patrickjahns
- [X] Add a new 'Unreleased' section in CHANGELOG.md https://github.com/owncloud/gallery/commit/93614a02c80f13a0bc014edcec933e71287b9038 - @pvince81
- [x] Create PR to merge changes back to `master` https://github.com/owncloud/gallery/pull/770

**Comment by DeepDiver1975** [comment]
needs merge: https://github.com/owncloud/gallery/pull/767

**Comment by DeepDiver1975** [comment]
[gallery.tar.gz](https://github.com/owncloud/gallery/files/2148869/gallery.tar.gz)
