### ISSUE TITLE
Test Results for Gallery App v. 16.1.0.

### ISSUE THREAD

**Issue by davitol** [owncloud/gallery#771]
| Test Case                                | Expected Result                          | Result Firefox | Result Safari  | Result Edge    | Result Chrome   | Result IE11 | Related Comment |
| ---------------------------------------- | ---------------------------------------- | -------------- | -------------- | -------------- | -------------- | ------------- | --------------- |
| Click on an image              | Large, zoomable previews without problems. | ✅  |  ✅ | ✅ |  ✅             | ✅            |                 |
| Sort images by name              | Images are sorted without problems. | ✅  |  ✅ | ✅ |  ✅             | ✅            |                 |
| Sort images by date              | Images are sorted without problems. | ✅  |  ✅ | ✅ |  ✅             | ✅            |                 |
| Download straight an image from the slideshow or the gallery             | Images are sorted without problems. | ✅  |  ✅ | ✅ |  ✅             | ✅            |                 |
| Browse between the gallery and the files view             | You can browse without problems | ✅  |  ✅ | ✅ |  ✅             | ✅            |                 |

**Comment by davitol** [comment]
**Mean Scenarios**

- [x] Update gallery from an old version
- [x] Update gallery from a tarball via CLI  ```sudo -u www-data ./occ market:install -l /pathtotarball/tarball```
- [x] Check gallery app works with files_S3 https://github.com/owncloud/files_primary_s3/issues/72
- ❌ Check images inside a shared folder via link are shown
- ❌  Check images set as hidden files are not shown when 'show hidden files option' is not active

**Comment by davitol** [comment]
**Know issues**
- [ ] Images inside a folder shared via link are not shown in Gallery app https://github.com/owncloud/gallery/issues/774
- [ ] Images set as hidden files should not be shown in Gallery app when 'show hidden files option' is not active https://github.com/owncloud/gallery/issues/775
